default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: questz_development

test:
  <<: *default
  database: questz_test

production:
  <<: *default
  database: questz_production
  username: questz
  password: <%= ENV['DATABASE_URL'] %>
