\w*fuck[ae]r?s?
fag\w*
cunt\w*
as*hole\w*
\w*bitch\w*
fudge ?pack\w*
bastards?
\w*fuck\w*
\w*fcuk\w*
\w*fuk\w*
\w*shit\w*
ass+(es)?
asshol\w*
\w*bitch\w*
cunt\w*
fag\w*
sex\w*
blow ?job\w*
fellat\w*
felch\w*
\w*fuck\w*
wank\w*
cocks?
cock suck\w*
poll ?smok\w*
dicks?
fudge ?pack\w*
rim ?job\w*
knob ?gobbl\w*
anal
rectums?
ass+
as*hole\w*
ballsacks?
scrotums?
bollocks
penis(es)?
boners?
pricks?
knobends?
manhoods?
wieners?
breasts?
tit(t(ie|y))?s?
boob\w*
honkers?
cleavages?
vagina\w*
puss(y|ies|ee)
muffs?
cunt\w*
twats?
clit\w*
quims?
labias?
buttplugs?
dildos?
homos?
sluts?
whor\w*
skank\w*
g+h?[ae]ys?
dykes?
fag\w*
cumm?(ing|er)?
jizz\w*
pubes?
pubic
smegma
boy ?butter
stab(ing|ed|s|ber)?
kill\w*
beat ?up
beat the \w+ out of
fuck ?\w* up
murder\w*
genocide
shoot (him|her|it|me|us|them)
shot (him|her|it|me|us|them)
gun\w*
phasers?
death( ray)?